name: Ansible CI Test

on:
  push:
    branches: [main]

jobs:
  ansible-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Verify Ansible installation
        run: ansible --version

